version: 2

sources:
  - name: profitwell
    schema: "{{ var('profitwell_schema', 'profitwell') }}"
    database: "{{ var('profitwell_database', target.database) }}"
    tables: 
      - name: active_customers
        identifier: "{{ var('active_customers_tbl', 'active_customers') }}"

      - name: average_revenue_per_user
        identifier: "{{ var('average_revenue_per_user_tbl', 'average_revenue_per_user') }}"

      - name: churned_customers
        identifier: "{{ var('churned_customers_tbl', 'churned_customers') }}"

      - name: churned_recurring_revenue
        identifier: "{{ var('churned_recurring_revenue_tbl', 'churned_recurring_revenue') }}"

      - name: downgraded_customers
        identifier: "{{ var('downgraded_customers_tbl', 'downgraded_customers') }}"

      - name: downgraded_recurring_revenue
        identifier: "{{ var('downgraded_recurring_revenue_tbl', 'downgraded_recurring_revenue') }}"
      
      - name: new_customers
        identifier: "{{ var('new_customers_tbl', 'new_customers') }}"
      
      - name: new_recurring_revenue
        identifier: "{{ var('new_recurring_revenue_tbl', 'new_recurring_revenue') }}"

      - name: recurring_revenue
        identifier: "{{ var('recurring_revenue_tbl', 'recurring_revenue') }}"
